server:
  port: 8989
# Database connect
spring:
  datasource:
    url: jdbc:postgresql://localhost:5332/multimodal_b2b_db
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQL10Dialect
        default_schema: public
    show-sql: true
# CORS
cors:
  allowed-origins: "*"
  allowed-methods: "*"
  allowed-headers: "*"
  exposed-headers: "*"